### ISSUE TITLE
Readme/code remarks

### ISSUE THREAD

**Issue by baskapteijn** [Erriez/ErriezTimestamp#3]
1:
Micros() might not be 1 microseconds resolution, depends on the target. It could be 4 microseconds according to the arduino website. This should be made clear in both doxygen and the readme, or that micros() is used for timestamping and its resolution is depending in the target.
"Please refer to the description of these functions for the maximum possible duration:", so maybe add here "and minimum resolution".

2:
Isnt there a way to store the delta data (start to end) in the class as well? Or is this an unusual practice. Reason being: now you still have to create a seperate storage variable for delta, while this is the most used reason for timestamping. Would be nice to contain it in the class somehow as a variable thats updated on calling stop/end.

3:
This is more a matter of what i am used to and see most commonly done, i would call the timestamp functions start and end, because you are not actually stopping something but just ending a stamping delta. 

4:
Wouldnt it be nice to have an override function to print your own deltatimestamp instead of (again) internally creating 1 before printing? So a .print() and a .print(mydelta) function (both micros and millis). For my usecases this would be most usefull.

5:
This is more common for all your cpp projects, and I might lack c++ knowledge so forgive me for asking dumb questions, but why do you not have a destructor in most of your classes? Is the class instance cleaned up nicely even without destructor, might someone want to do that? Or will this cause memory leaks?
Edit: now i see. Compiler makes a destructor if you dont create one. So 
should be fine as long as you 
dont malloc i guess?
https://en.cppreference.com/w/cpp/language/destructor

6:
How much overhead (time) would calling your functions with this class have (nanoseconds? 1 microsecond?). Also system/clock dependent, i know, but might be relevant on low end devices. Maybe add a warning for low end/slow devices that this might actually introduce some unwanted delay when measuring in the lower microsecond regions.

7:
Interrupts might come in just when you stored the delta. This can still give sime extra microseconds delay that you will not return in the delta. No need to fix, you cant, but maybe add a disclaimer somewhere.

**Comment by Erriez** [comment]
Can you create separate issues for each topic? This makes it easier to start conversations and assign issues.

Thanks!

**Comment by baskapteijn** [comment]
I will create 5 separate items then and remove this one. The 5th comment is probably no longer an issue, and 6th and 7th can be combined.

**Comment by baskapteijn** [comment]
Split-up in some separate issues.
