### ISSUE TITLE
Micros resolution might be != 1 depending on the platform

### ISSUE THREAD

**Issue by baskapteijn** [Erriez/ErriezTimestamp#5]
Micros() might not be 1 microseconds resolution, depends on the target. It could be 4 microseconds according to the Arduino website. This should be made clear in both Doxygen and the readme, or that micros() is used for time-stamping and its resolution is depending in the target.

So for example extend this description:

> Please refer to the description of these functions for the maximum possible duration:

To:

> Please refer to the description of these functions for the maximum possible duration and minimum resolution:

**Comment by Erriez** [comment]
Thanks for your feedback. Fixed in commit d9764b6.

**Comment by baskapteijn** [comment]
Perfect :+1:
