### ISSUE TITLE
Class function calling overhead

### ISSUE THREAD

**Issue by baskapteijn** [Erriez/ErriezTimestamp#7]
When using the timestamp library to measure very short times (< 10us) the overhead of just calling the libraries functions might introduce a significant addition to the timestamp delta. This cannot be apprehended, however it should be added as a disclaimer to the readme/class documentation.

You could go as far as to measure and noting overhead for a few microcontrollers (per function), but I would just add a disclaimer stating that for delta's < 10microseconds there might be significant overhead in using this library (at least on low end 8bit micro's).

**Comment by Erriez** [comment]
Fixed in commit 3c946fe.
